training_args:
    evaluation_strategy: "no"
    # save_strategy: "epoch"
    learning_rate: 5.6e-5
    per_device_train_batch_size: 1
    per_device_eval_batch_size: 1
    weight_decay: 0.01
    num_train_epochs: 15
    logging_strategy: "epoch"
    predict_with_generate: True
    save_total_limit: 3
    fp16: True
    push_to_hub: False